<?php
/**
 * @package pro
 */
?>
<ul class="progression-studios-social-icons<?php if (get_theme_mod( 'progression_studios_footer_icon_text', 'off') == 'off') : ?> progression-studios-footer-icon-text-hide<?php endif; ?><?php if (get_theme_mod( 'progression_studios_footer_icon_location_align') == 'right') : ?> progression-studios-footer-icon-align-right<?php endif; ?><?php if (get_theme_mod( 'progression_studios_footer_icon_location_align') == 'left') : ?> progression-studios-footer-icon-align-left<?php endif; ?>">
	<?php if (get_theme_mod( 'progression_studios_footer_facebook')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_facebook')); ?>" target="_blank" class="progression-studios-facebook" title="<?php echo esc_html__( 'Facebook', 'viseo-progression' ); ?>"><i class="fa fa-facebook"></i><span><?php echo esc_html__( 'Facebook', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_twitter')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_twitter')); ?>" target="_blank" class="progression-studios-twitter" title="<?php echo esc_html__( 'Twitter', 'viseo-progression' ); ?>"><i class="fa fa-twitter"></i><span><?php echo esc_html__( 'Twitter', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_instagram')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_instagram')); ?>" target="_blank" class="progression-studios-instagram" title="<?php echo esc_html__( 'Instagram', 'viseo-progression' ); ?>"><i class="fa fa-instagram"></i><span><?php echo esc_html__( 'Instagram', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_spotify')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_spotify')); ?>" target="_blank" class="progression-studios-spotify" title="<?php echo esc_html__( 'Spotify', 'viseo-progression' ); ?>"><i class="fa fa-spotify"></i><span><?php echo esc_html__( 'Spotify', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_youtube' )) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_youtube')); ?>" target="_blank" class="progression-studios-youtube" title="<?php echo esc_html__( 'Youtube', 'viseo-progression' ); ?>"><i class="fa fa-youtube-square"></i><span><?php echo esc_html__( 'Youtube', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_vimeo')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_vimeo')); ?>" target="_blank" class="progression-studios-vimeo" title="<?php echo esc_html__( 'Vimeo', 'viseo-progression' ); ?>"><i class="fa fa-vimeo"></i><span><?php echo esc_html__( 'Vimeo', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_google_plus')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_google_plus')); ?>" target="_blank" class="progression-studios-google-plus" title="<?php echo esc_html__( 'Google+', 'viseo-progression' ); ?>"><i class="fa fa-google-plus"></i><span><?php echo esc_html__( 'Google+', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_pinterest')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_pinterest')); ?>" target="_blank" class="progression-studios-pinterest" title="<?php echo esc_html__( 'Pinterest', 'viseo-progression' ); ?>"><i class="fa fa-pinterest"></i><span><?php echo esc_html__( 'Pinterest', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_soundcloud')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_soundcloud')); ?>" target="_blank" class="progression-studios-soundcloud" title="<?php echo esc_html__( 'Soundcloud', 'viseo-progression' ); ?>"><i class="fa fa-soundcloud"></i><span><?php echo esc_html__( 'Soundcloud', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_linkedin')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_linkedin')); ?>" target="_blank" class="progression-studios-linkedin" title="<?php echo esc_html__( 'LinkedIn', 'viseo-progression' ); ?>"><i class="fa fa-linkedin"></i><span><?php echo esc_html__( 'LinkedIn', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_snapchat')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_snapchat')); ?>" target="_blank" class="progression-studios-snapchat" title="<?php echo esc_html__( 'Snapchat', 'viseo-progression' ); ?>"><i class="fa fa-snapchat-ghost"></i><span><?php echo esc_html__( 'Snapchat', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_tumblr')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_tumblr')); ?>" target="_blank" class="progression-studios-tumblr" title="<?php echo esc_html__( 'Tumblr', 'viseo-progression' ); ?>"><i class="fa fa-tumblr"></i><span><?php echo esc_html__( 'Tumblr', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_flickr')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_flickr')); ?>" target="_blank" class="progression-studios-flickr" title="<?php echo esc_html__( 'Flickr', 'viseo-progression' ); ?>"><i class="fa fa-flickr"></i><span><?php echo esc_html__( 'Flickr', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_dribbble')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_dribbble')); ?>" target="_blank" class="progression-studios-dribbble" title="<?php echo esc_html__( 'Dribbble', 'viseo-progression' ); ?>"><i class="fa fa-dribbble"></i><span><?php echo esc_html__( 'Dribbble', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_vk')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_vk')); ?>" target="_blank" class="progression-studios-vk" title="<?php echo esc_html__( 'VK', 'viseo-progression' ); ?>"><i class="fa fa-vk"></i><span><?php echo esc_html__( 'VK', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_wordpress')) : ?><li><a href="<?php echo esc_url(get_theme_mod('progression_studios_footer_wordpress')); ?>" target="_blank" class="progression-studios-wordpress" title="<?php echo esc_html__( 'WordPress', 'viseo-progression' ); ?>"><i class="fa fa-wordpress"></i><span><?php echo esc_html__( 'WordPress', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_footer_houzz')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_houzz')); ?>" target="_blank" class="progression-studios-houzz" title="<?php echo esc_html__( 'Houzz', 'viseo-progression' ); ?>"><i class="fa fa-houzz"></i><span><?php echo esc_html__( 'Houzz', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_behance')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_behance')); ?>" target="_blank" class="progression-studios-behance" title="<?php echo esc_html__( 'Behance', 'viseo-progression' ); ?>"><i class="fa fa-behance"></i><span><?php echo esc_html__( 'Behance', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_github')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_github')); ?>" target="_blank" class="progression-studios-github" title="<?php echo esc_html__( 'GitHub', 'viseo-progression' ); ?>"><i class="fa fa-github"></i><span><?php echo esc_html__( 'Github', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_lastfm')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_lastfm')); ?>" target="_blank" class="progression-studios-lastfm" title="<?php echo esc_html__( 'LastFM', 'viseo-progression' ); ?>"><i class="fa fa-lastfm"></i><span><?php echo esc_html__( 'LastFM', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_medium')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_medium')); ?>" target="_blank" class="progression-studios-medium" title="<?php echo esc_html__( 'Medium', 'viseo-progression' ); ?>"><i class="fa fa-medium"></i><span><?php echo esc_html__( 'Medium', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_tripadvisor')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_tripadvisor')); ?>" target="_blank" class="progression-studios-tripadvisor" title="<?php echo esc_html__( 'Trip Advisor', 'viseo-progression' ); ?>"><i class="fa fa-tripadvisor"></i><span><?php echo esc_html__( 'Trip Advisor', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_twitch')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_twitch')); ?>" target="_blank" class="progression-studios-twitch" title="<?php echo esc_html__( 'Twitch', 'viseo-progression' ); ?>"><i class="fa fa-twitch"></i><span><?php echo esc_html__( 'Twitch', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	<?php if (get_theme_mod( 'progression_studios_footer_yelp')) : ?><li><a href="<?php echo esc_attr(get_theme_mod('progression_studios_footer_yelp')); ?>" target="_blank" class="progression-studios-yelp" title="<?php echo esc_html__( 'Yelp', 'viseo-progression' ); ?>"><i class="fa fa-yelp"></i><span><?php echo esc_html__( 'Yelp', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	
	<?php if (get_theme_mod( 'progression_studios_footer_mail')) : ?><li><a href="mailto:<?php echo esc_attr(get_theme_mod('progression_studios_footer_mail')); ?>" class="progression-studios-mail" title="<?php echo esc_html__( 'Email', 'viseo-progression' ); ?>"><i class="fa fa-envelope"></i><span><?php echo esc_html__( 'Email', 'viseo-progression' ); ?></span></a></li><?php endif; ?>
	
</ul><!-- close .progression-studios-social-icons -->